// Generated by CoffeeScript 1.9.1
var ReactCoffeeCompiler, coffeescript, transform;

transform = require('coffee-react-transform');

coffeescript = require('coffee-script');

module.exports = ReactCoffeeCompiler = (function() {
  ReactCoffeeCompiler.prototype.brunchPlugin = true;

  ReactCoffeeCompiler.prototype.type = 'javascript';

  ReactCoffeeCompiler.prototype.extension = 'cjsx';

  ReactCoffeeCompiler.prototype.pattern = /\.cjsx/;

  function ReactCoffeeCompiler(config) {
    var ref, ref1, ref2;
    this.config = config;
    this.includeHeader = ((ref = this.config) != null ? (ref1 = ref.plugins) != null ? (ref2 = ref1.react) != null ? ref2.autoIncludeCommentBlock : void 0 : void 0 : void 0) === true;
  }

  ReactCoffeeCompiler.prototype.compile = function(data, path, callback) {
    var err, output, source;
    source = this.includeHeader ? "# @cjsx React.DOM \n" + data : data;
    try {
      output = transform(source);
      output = coffeescript.compile(output, {
        bare: true
      });
    } catch (_error) {
      err = _error;
      console.log("ERROR", err);
      return callback(err.toString());
    }
    return callback(null, output);
  };

  return ReactCoffeeCompiler;

})();
