// Generated by CoffeeScript 1.7.1
var ReactCoffeeCompiler, coffeescript, transform;

transform = require('coffee-react-transform');

coffeescript = require('coffee-script');

module.exports = ReactCoffeeCompiler = (function() {
  ReactCoffeeCompiler.prototype.brunchPlugin = true;

  ReactCoffeeCompiler.prototype.type = 'javascript';

  ReactCoffeeCompiler.prototype.extension = 'cjsx';

  ReactCoffeeCompiler.prototype.pattern = /\.cjsx/;

  function ReactCoffeeCompiler(config) {
    var _ref, _ref1, _ref2;
    this.config = config;
    this.includeHeader = ((_ref = this.config) != null ? (_ref1 = _ref.plugins) != null ? (_ref2 = _ref1.react) != null ? _ref2.autoIncludeCommentBlock : void 0 : void 0 : void 0) === true;
  }

  ReactCoffeeCompiler.prototype.compile = function(params, callback) {
    var err, output, source;
    source = this.includeHeader ? "# @cjsx React.DOM \n" + params.data : params.data;
    try {
      output = transform(source);
      output = coffeescript.compile(output, {});
    } catch (_error) {
      err = _error;
      console.log("ERROR", err);
      return callback(err.toString());
    }
    return callback(null, {
      data: output
    });
  };

  return ReactCoffeeCompiler;

})();
